config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'

  devise_for :users
  root 'movies#index'
  resources :movies do 
  	resources :reviews ,except: [:show, :index]
 	end

 	get "/movie/search"  => "movies#search"
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :reviews
	belongs_to :user
	has_attached_file :image, styles: { medium: "300x450#", thumb: "200x300#" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  	ratyrate_rateable "rating"
  	
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :movie
	belongs_to :user


end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  ratyrate_rater
	has_many :movies
	has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
  	'/movies'
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :authenticate_user! , except: [:index, :show]
	def index
		@movies = Movie.all.order("created_at DESC") 
	end

	def show
		@movie = Movie.find(params[:id])
		@reviews = Review.where(movie_id: @movie.id).order("created_at DESC")
	end

	def new
		@movie = current_user.movies.build
	end

	def edit
		@movie = Movie.find(params[:id])
	end

	def create
		@movie = current_user.movies.build(movie_params)
		if @movie.save
	    redirect_to @movie
	  else
	    render 'new'
	  end
	end

	def search
		@movies = Movie.where("movie LIKE ? OR director LIKE ? ","%#{params[:id]}%", "%#{params[:id]}%").order("created_at DESC")
	end

	def update
		@movie = Movie.find(params[:id])
		if @movie.user_id == current_user.id
			if @movie.update(movie_params)
		    redirect_to @movie
		  else
		    render 'edit'
		  end
		else 
			flash[:error] = "You are not authorized to edit this movie"
			redirect_to @movie
		end
	end

	def destroy
		@movie = Movie.find(params[:id])
		@movie.destroy
		redirect_to movies_path
	end

	private
		def movie_params
			params.require(:movie).permit(:movie, :description, :director, :cast, :duration, :year, :image)
		end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_i, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :authenticate_user!
	before_action :set_movie
	def new
	
		@review = Review.new
	end

	def edit
		@review = Review.find(params[:id])
	end

	def create
		@review = Review.new(review_params)
		@review.user_id = current_user.id
		@review.movie_id = @movie.id
		if @review.save
			redirect_to @movie
		else 
			render 'new'
		end
	end

	def update
		@review = Review.find(params[:id])
		if @review.update(review_params)
			redirect_to @movie
		else
			render 'edit'
		end
	end

	def destroy
		@review = Review.find(params[:id])
		@review.destroy
		redirect_to @movie
	end

	private 
		def review_params
			params.require(:review).permit(:review, :rating)
		end

		def set_movie
			@movie = Movie.find(params[:movie_id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class= "navbar navbar-default" role="navigation" >
	  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"></a>
    </div>
    <ul class="nav navbar-nav">
    <li class="navbar-brand" style= "font-style:italic" ><%= "MoviemaniaC"%></li>
      <li><%= link_to "Movies", root_path, class: "active" %>
      
			<% if user_signed_in? %>
				<li><%= link_to "New movie", new_movie_path, class: "active" %></li>					
				
				<li><%= link_to "Account", edit_user_registration_path %></li>

			<% else %>
				<li><%= link_to "Signup", new_user_registration_path, class: "active" %></li>
				<li><%= link_to "Signin", new_user_session_path, class: "active" %></li>
			<% end %>	

			
    </ul>
				

		<ul class="nav navbar-nav" style="float:right">
			<% if user_signed_in? %>
					
					<li><%= link_to "Signout", destroy_user_session_path , method: :delete %></li>
				
				<% end %>		
		</ul>
		<form class="navbar-form navbar-right" role="search" style="float:right" action= "/movie/search" >
			<div class="form-group">

                <input type="text" class="form-control" placeholder="Search" name="id">

                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>

		</form>
  </div>
	
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moviemaniac</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style>
  	a:hover{text-decoration: none }
  </style>
</head>
<body>
	<%= render 'layouts/header' %>
	<% flash.each do |name, msg | %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>
	<div class = "container">
	  <%= yield %>
	</div>

</body>
</html>

app/views/movies/_form.html.erb
  <%= form_for @movie, html: { multipart: true } do |f| %>
   
    <% if @movie.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@movie.errors.count, "error") %> prohibited
          this movie from being saved:
        </h2>
        <ul>
          <% @movie.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
      <%= f.label :movie %><br>
      <%= f.text_field :movie %>
    </p>
   
    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </p>

    <p>
      <%= f.label :director %><br>
      <%= f.text_field :director %>
    </p>

    <p>
      <%= f.label :cast %><br>
      <%= f.text_field :cast %>
    </p>

    <p>
      <%= f.label :duration %><br>
      <%= f.text_field :duration %>
    </p>

    <p>
      <%= f.label :year %><br>
      <%= f.text_field :year %>
    </p>

     <p><%= f.file_field :image %></p>

   
    <p >
      <%= f.submit :class=> "btn btn-primary" %>
    </p>
   
  <% end %>

app/views/movies/edit.html.erb
<div class="alert  alert-info" style="width:26%; margin-left:38%">
	<h3>
		Edit movie
	</h3>

	<%= render 'form' %>
	
	<%= link_to 'Back', movie_path(@movie) , class: "btn btn-default"%>
</div>

app/views/movies/index.html.erb
<% if !user_signed_in? %>
	<div class = "jumbotron">
		<h1>Your favorite movies Reviewed</h1>
		<p>"Troy: You see, Lainie, this is all we need. . .couple of smokes, a cup of coffee. . .and a little bit of conversation. You and me and five bucks.- Reality Bites(1998)"</p>
		<div align="center">
			<p><%= link_to "Signin to write a review", new_user_session_path ,class: "btn btn-primary btn-lg" %></p>
		</div>
	</div>
<% end %>

<div class = "row">
	<% @movies.each do |movie| %>
		<div class = "col-sm-6 col-md-3">
			<div class = "thumbnail" style="float=">			
				<%= link_to (image_tag movie.image.url(:medium), class: "image"), movie  %>
				
			</div>
			<br/>
		</div>
	<% end %>
</div>

app/views/movies/new.html.erb
<div class="alert  alert-info" style="width:26%; margin-left:38%">
	<div class = "container">
	<h3>
		New movie
	</h3>
	<%= render 'form' %>
	<%= link_to 'Home', movies_path , class: "btn btn-default"%>
	</div>
</div>

app/views/movies/search.html.erb
<% if !user_signed_in? %>
	<div class = "jumbotron">
		<h1>Your favorite movies Reviewed</h1>
		<p>"Troy: You see, Lainie, this is all we need. . .couple of smokes, a cup of coffee. . .and a little bit of conversation. You and me and five bucks."</p>
		<div align="center">
			<p><%= link_to "Signin to write a review", new_user_session_path ,class: "btn btn-primary btn-lg" %></p>
		</div>
	</div>
<% end %>
 <div class = "row">
 <% if @movies.blank? %>
 	<h3>OOPS! No movies found. </h3>
 <% else %>
	<% @movies.each do |movie| %>
		<div class = "col-sm-6 col-md-3">
			<div class = "thumbnail" style="float=">			
				<%= link_to (image_tag movie.image.url(:medium), class: "image"), movie %><br/>
				<%= link_to movie.movie %>
			</div>
		</div>
		<% end %>
	<% end %>
</div>

app/views/movies/show.html.erb
<div class = "panel panel-default">
	<div class ="panel-body">
		<div class ="row">
			<div class= "col-md-4">
				<%= image_tag @movie.image.url(:medium) %>
				<div class= "table-responsive">	
					<table class = "table">
						<tbody>
							<tr>
								<td><strong>Title</strong></td>
								<td><%= @movie.movie %></td>
							</tr>
							<tr>
								<td><strong>Director</strong></td>
								<td><%= @movie.director %></td>
							</tr>
							<tr>
								<td><strong>Cast</strong></td>
								<td><%= @movie.cast %></td>
							</tr>
							<tr>
								<td><strong>Description</strong></td>
								<td><%= @movie.description %></td>
							</tr>
							<tr>
								<td><strong>Duration</strong></td>
								<td><%= @movie.duration %></td>
							</tr>
							<tr>
								<td><strong>Theatrical Release</strong></td>
								<td><%= @movie.year %></td>
							</tr>
						</tbody>
					</table>
					<%= link_to "Write a review", new_movie_review_path(@movie) %>
				</div>
			</div>
			<div class="col-md-7 col-md-offset-1">
				<h2 class= "review-title"><%= @movie.movie %></h2>
				<p>(<%=@movie.year %>)</p>
				<p><%= @movie.description %></p>
				<div class="star-rating" ><%= rating_for @movie, 'rating',disable_after_rate: true, enable_half: true, half_show: true %></div>
				
				<% if @reviews.blank? %>
					<h4>No reviews just yet, would you like to add the first?</h4>
					<%= link_to "Write a review ", new_movie_review_path(@movie), class: "btn btn-primary" %>
				<% else %>
					<% @reviews.each do |review| %>
						<div class="reviews">
							<p><%= review.review %></p>
							<% if user_signed_in? %>
								<% if review.user_id == current_user.id %>
									<%= link_to "edit", edit_movie_review_path(@movie, review) %>
									<%= link_to "Delete", movie_review_path(@movie, review), method: "delete" %>

								<% elsif current_user.id == 1 %>
									<%= link_to "edit", edit_movie_review_path(@movie, review) %>
									<%= link_to "Delete", movie_review_path(@movie, review), method: "delete" %>
								<% end %>
							<% end %>
						</div>
					<% end %>
				<% end%>
			</div>
		</div>
	</div>
</div>





<% if user_signed_in? %>

	<% if @movie.user_id == current_user.id  %>

		<%= link_to 'Edit', edit_movie_path(@movie) %>
		<%= link_to 'Delete', movie_path(@movie), method: :delete, data: {confirm: "Are you sure?"} %>
	<% elsif current_user.id == 1 %>
		<%= link_to 'Edit', edit_movie_path(@movie) %>
		<%= link_to 'Delete', movie_path(@movie), method: :delete, data: {confirm: "Are you sure?"} %>
		
	<% end %>
<% end %>  
<%= link_to 'Back', movies_path %>

app/views/reviews/edit.html.erb
<div class="alert  alert-info" style="width:26%; margin-left:38%">
	<h4>Edit Review</h4>
	<%= form_for @review , url: movie_review_path(@movie, @review), method: "patch" do |f| %>
		
		<p>
			Comment<br/>
			<%= f.text_area :review %>
			
		</p>
		<p><%= f.submit:class=> "btn btn-primary" %></p>
	<% end %>
	<%= link_to "back", movie_path(@movie), class: "btn btn-default" %>

</div>

app/views/reviews/new.html.erb
<div class="alert  alert-info" style="width:26%; margin-left:38%">
	<h4>New review</h4>
	<%= form_for @review , url: movie_reviews_path(@movie), method: "post" do |f| %>
		
		<p>
			Comment<br/>
			<%= f.text_area :review %>

			
		</p>
		<p><%= f.submit :class=> "btn btn-primary" %></p>
	<% end %>
	<!-- <p>Please rate the movie once your comment is saved.</p> -->
	<%= link_to "back", movie_path(@movie), class: "btn btn-default" %>
</div>